/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OpportunityCategory = IDL.Variant({
  'other' : IDL.Null,
  'sales' : IDL.Null,
  'freelance' : IDL.Null,
  'digital' : IDL.Null,
  'services' : IDL.Null,
});
export const Time = IDL.Int;
export const Opportunity = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'category' : OpportunityCategory,
  'requirements' : IDL.Text,
  'estimatedAmount' : IDL.Text,
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Application = IDL.Record({
  'id' : IDL.Text,
  'status' : ApplicationStatus,
  'applicantName' : IDL.Text,
  'applicantId' : IDL.Principal,
  'createdAt' : Time,
  'opportunityId' : IDL.Text,
  'message' : IDL.Text,
  'applicantEmail' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyToOpportunity' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOpportunity' : IDL.Func(
      [IDL.Text, IDL.Text, OpportunityCategory, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'deleteOpportunity' : IDL.Func([IDL.Text], [], []),
  'getActiveOpportunities' : IDL.Func([], [IDL.Vec(Opportunity)], ['query']),
  'getAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'getAllOpportunities' : IDL.Func([], [IDL.Vec(Opportunity)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'getOpportunityById' : IDL.Func([IDL.Text], [Opportunity], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleOpportunityStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'updateApplicationStatus' : IDL.Func([IDL.Text, ApplicationStatus], [], []),
  'updateOpportunity' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, OpportunityCategory, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OpportunityCategory = IDL.Variant({
    'other' : IDL.Null,
    'sales' : IDL.Null,
    'freelance' : IDL.Null,
    'digital' : IDL.Null,
    'services' : IDL.Null,
  });
  const Time = IDL.Int;
  const Opportunity = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'category' : OpportunityCategory,
    'requirements' : IDL.Text,
    'estimatedAmount' : IDL.Text,
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Application = IDL.Record({
    'id' : IDL.Text,
    'status' : ApplicationStatus,
    'applicantName' : IDL.Text,
    'applicantId' : IDL.Principal,
    'createdAt' : Time,
    'opportunityId' : IDL.Text,
    'message' : IDL.Text,
    'applicantEmail' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyToOpportunity' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOpportunity' : IDL.Func(
        [IDL.Text, IDL.Text, OpportunityCategory, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deleteOpportunity' : IDL.Func([IDL.Text], [], []),
    'getActiveOpportunities' : IDL.Func([], [IDL.Vec(Opportunity)], ['query']),
    'getAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'getAllOpportunities' : IDL.Func([], [IDL.Vec(Opportunity)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'getOpportunityById' : IDL.Func([IDL.Text], [Opportunity], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleOpportunityStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'updateApplicationStatus' : IDL.Func([IDL.Text, ApplicationStatus], [], []),
    'updateOpportunity' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, OpportunityCategory, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };