/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'id' : string,
  'status' : ApplicationStatus,
  'applicantName' : string,
  'applicantId' : Principal,
  'createdAt' : Time,
  'opportunityId' : string,
  'message' : string,
  'applicantEmail' : string,
}
export type ApplicationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Opportunity {
  'id' : string,
  'title' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'description' : string,
  'isActive' : boolean,
  'category' : OpportunityCategory,
  'requirements' : string,
  'estimatedAmount' : string,
}
export type OpportunityCategory = { 'other' : null } |
  { 'sales' : null } |
  { 'freelance' : null } |
  { 'digital' : null } |
  { 'services' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyToOpportunity' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOpportunity' : ActorMethod<
    [string, string, OpportunityCategory, string, string],
    undefined
  >,
  'deleteOpportunity' : ActorMethod<[string], undefined>,
  'getActiveOpportunities' : ActorMethod<[], Array<Opportunity>>,
  'getAllApplications' : ActorMethod<[], Array<Application>>,
  'getAllOpportunities' : ActorMethod<[], Array<Opportunity>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyApplications' : ActorMethod<[], Array<Application>>,
  'getOpportunityById' : ActorMethod<[string], Opportunity>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleOpportunityStatus' : ActorMethod<[string, boolean], undefined>,
  'updateApplicationStatus' : ActorMethod<
    [string, ApplicationStatus],
    undefined
  >,
  'updateOpportunity' : ActorMethod<
    [string, string, string, OpportunityCategory, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];